/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus.thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class proteusConstants {

  public static final Map<String,List<String>> isContainedBy = new HashMap<String,List<String>>();
  static {
    List<String> tmp226 = new ArrayList<String>();
    tmp226.add("collection");

    isContainedBy.put("page", tmp226);
    List<String> tmp227 = new ArrayList<String>();
    tmp227.add("page");
    tmp227.add("collection");

    isContainedBy.put("picture", tmp227);
    List<String> tmp228 = new ArrayList<String>();
    tmp228.add("page");
    tmp228.add("collection");

    isContainedBy.put("video", tmp228);
    List<String> tmp229 = new ArrayList<String>();
    tmp229.add("page");
    tmp229.add("collection");

    isContainedBy.put("audio", tmp229);
    List<String> tmp230 = new ArrayList<String>();
    tmp230.add("page");
    tmp230.add("picture");
    tmp230.add("video");
    tmp230.add("audio");
    tmp230.add("collection");

    isContainedBy.put("person", tmp230);
    List<String> tmp231 = new ArrayList<String>();
    tmp231.add("page");
    tmp231.add("picture");
    tmp231.add("video");
    tmp231.add("audio");
    tmp231.add("collection");

    isContainedBy.put("location", tmp231);
    List<String> tmp232 = new ArrayList<String>();
    tmp232.add("page");
    tmp232.add("picture");
    tmp232.add("video");
    tmp232.add("audio");
    tmp232.add("collection");

    isContainedBy.put("organization", tmp232);
    List<String> tmp233 = new ArrayList<String>();
    tmp233.add("page");
    tmp233.add("picture");
    tmp233.add("video");
    tmp233.add("audio");
    tmp233.add("collection");

    isContainedBy.put("miscellaneous", tmp233);
  }

  public static final Map<String,List<String>> contains = new HashMap<String,List<String>>();
  static {
    List<String> tmp234 = new ArrayList<String>();
    tmp234.add("page");
    tmp234.add("picture");
    tmp234.add("video");
    tmp234.add("audio");
    tmp234.add("person");
    tmp234.add("location");
    tmp234.add("organization");
    tmp234.add("miscellaneous");

    contains.put("collection", tmp234);
    List<String> tmp235 = new ArrayList<String>();
    tmp235.add("page");
    tmp235.add("picture");
    tmp235.add("video");
    tmp235.add("audio");
    tmp235.add("person");
    tmp235.add("location");
    tmp235.add("organization");
    tmp235.add("miscellaneous");

    contains.put("book", tmp235);
    List<String> tmp236 = new ArrayList<String>();
    tmp236.add("picture");
    tmp236.add("video");
    tmp236.add("audio");
    tmp236.add("person");
    tmp236.add("location");
    tmp236.add("organization");
    tmp236.add("miscellaneous");

    contains.put("page", tmp236);
    List<String> tmp237 = new ArrayList<String>();
    tmp237.add("person");
    tmp237.add("location");
    tmp237.add("organization");
    tmp237.add("miscellaneous");

    contains.put("picture", tmp237);
    List<String> tmp238 = new ArrayList<String>();
    tmp238.add("person");
    tmp238.add("location");
    tmp238.add("organization");
    tmp238.add("miscellaneous");

    contains.put("video", tmp238);
    List<String> tmp239 = new ArrayList<String>();
    tmp239.add("person");
    tmp239.add("location");
    tmp239.add("organization");
    tmp239.add("miscellaneous");

    contains.put("audio", tmp239);
  }

}
