/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ciir.proteus.thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TopicInfo implements org.apache.thrift.TBase<TopicInfo, TopicInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TopicInfo");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NUM_WORDS_FIELD_DESC = new org.apache.thrift.protocol.TField("num_words", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField NUM_PAGES_FIELD_DESC = new org.apache.thrift.protocol.TField("num_pages", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TopicInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TopicInfoTupleSchemeFactory());
  }

  public String name; // required
  public long num_words; // required
  public long num_pages; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    NUM_WORDS((short)2, "num_words"),
    NUM_PAGES((short)3, "num_pages");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // NUM_WORDS
          return NUM_WORDS;
        case 3: // NUM_PAGES
          return NUM_PAGES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUM_WORDS_ISSET_ID = 0;
  private static final int __NUM_PAGES_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NUM_WORDS, new org.apache.thrift.meta_data.FieldMetaData("num_words", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NUM_PAGES, new org.apache.thrift.meta_data.FieldMetaData("num_pages", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TopicInfo.class, metaDataMap);
  }

  public TopicInfo() {
  }

  public TopicInfo(
    String name,
    long num_words,
    long num_pages)
  {
    this();
    this.name = name;
    this.num_words = num_words;
    setNum_wordsIsSet(true);
    this.num_pages = num_pages;
    setNum_pagesIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TopicInfo(TopicInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.num_words = other.num_words;
    this.num_pages = other.num_pages;
  }

  public TopicInfo deepCopy() {
    return new TopicInfo(this);
  }

  @Override
  public void clear() {
    this.name = null;
    setNum_wordsIsSet(false);
    this.num_words = 0;
    setNum_pagesIsSet(false);
    this.num_pages = 0;
  }

  public String getName() {
    return this.name;
  }

  public TopicInfo setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public long getNum_words() {
    return this.num_words;
  }

  public TopicInfo setNum_words(long num_words) {
    this.num_words = num_words;
    setNum_wordsIsSet(true);
    return this;
  }

  public void unsetNum_words() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUM_WORDS_ISSET_ID);
  }

  /** Returns true if field num_words is set (has been assigned a value) and false otherwise */
  public boolean isSetNum_words() {
    return EncodingUtils.testBit(__isset_bitfield, __NUM_WORDS_ISSET_ID);
  }

  public void setNum_wordsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUM_WORDS_ISSET_ID, value);
  }

  public long getNum_pages() {
    return this.num_pages;
  }

  public TopicInfo setNum_pages(long num_pages) {
    this.num_pages = num_pages;
    setNum_pagesIsSet(true);
    return this;
  }

  public void unsetNum_pages() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUM_PAGES_ISSET_ID);
  }

  /** Returns true if field num_pages is set (has been assigned a value) and false otherwise */
  public boolean isSetNum_pages() {
    return EncodingUtils.testBit(__isset_bitfield, __NUM_PAGES_ISSET_ID);
  }

  public void setNum_pagesIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUM_PAGES_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case NUM_WORDS:
      if (value == null) {
        unsetNum_words();
      } else {
        setNum_words((Long)value);
      }
      break;

    case NUM_PAGES:
      if (value == null) {
        unsetNum_pages();
      } else {
        setNum_pages((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case NUM_WORDS:
      return Long.valueOf(getNum_words());

    case NUM_PAGES:
      return Long.valueOf(getNum_pages());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case NUM_WORDS:
      return isSetNum_words();
    case NUM_PAGES:
      return isSetNum_pages();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TopicInfo)
      return this.equals((TopicInfo)that);
    return false;
  }

  public boolean equals(TopicInfo that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_num_words = true;
    boolean that_present_num_words = true;
    if (this_present_num_words || that_present_num_words) {
      if (!(this_present_num_words && that_present_num_words))
        return false;
      if (this.num_words != that.num_words)
        return false;
    }

    boolean this_present_num_pages = true;
    boolean that_present_num_pages = true;
    if (this_present_num_pages || that_present_num_pages) {
      if (!(this_present_num_pages && that_present_num_pages))
        return false;
      if (this.num_pages != that.num_pages)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_name = true && (isSetName());
    builder.append(present_name);
    if (present_name)
      builder.append(name);

    boolean present_num_words = true;
    builder.append(present_num_words);
    if (present_num_words)
      builder.append(num_words);

    boolean present_num_pages = true;
    builder.append(present_num_pages);
    if (present_num_pages)
      builder.append(num_pages);

    return builder.toHashCode();
  }

  public int compareTo(TopicInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TopicInfo typedOther = (TopicInfo)other;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(typedOther.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, typedOther.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNum_words()).compareTo(typedOther.isSetNum_words());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNum_words()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.num_words, typedOther.num_words);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNum_pages()).compareTo(typedOther.isSetNum_pages());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNum_pages()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.num_pages, typedOther.num_pages);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TopicInfo(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("num_words:");
    sb.append(this.num_words);
    first = false;
    if (!first) sb.append(", ");
    sb.append("num_pages:");
    sb.append(this.num_pages);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TopicInfoStandardSchemeFactory implements SchemeFactory {
    public TopicInfoStandardScheme getScheme() {
      return new TopicInfoStandardScheme();
    }
  }

  private static class TopicInfoStandardScheme extends StandardScheme<TopicInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TopicInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NUM_WORDS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.num_words = iprot.readI64();
              struct.setNum_wordsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NUM_PAGES
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.num_pages = iprot.readI64();
              struct.setNum_pagesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TopicInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NUM_WORDS_FIELD_DESC);
      oprot.writeI64(struct.num_words);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NUM_PAGES_FIELD_DESC);
      oprot.writeI64(struct.num_pages);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TopicInfoTupleSchemeFactory implements SchemeFactory {
    public TopicInfoTupleScheme getScheme() {
      return new TopicInfoTupleScheme();
    }
  }

  private static class TopicInfoTupleScheme extends TupleScheme<TopicInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TopicInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetName()) {
        optionals.set(0);
      }
      if (struct.isSetNum_words()) {
        optionals.set(1);
      }
      if (struct.isSetNum_pages()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetNum_words()) {
        oprot.writeI64(struct.num_words);
      }
      if (struct.isSetNum_pages()) {
        oprot.writeI64(struct.num_pages);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TopicInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.num_words = iprot.readI64();
        struct.setNum_wordsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.num_pages = iprot.readI64();
        struct.setNum_pagesIsSet(true);
      }
    }
  }

}

